python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 24, "seq_len": 36, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 36, "seq_len": 36, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 48, "seq_len": 36, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 60, "seq_len": 36, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 24, "seq_len": 104, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 36, "seq_len": 104, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 48, "seq_len": 104, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Wike2000.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 60, "seq_len": 104, "is_train": 1, "enc_in": 2000, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "Wike2000", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Wike2000/UniTime"
