python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 24, "seq_len": 36, "label_len": 18, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 36, "seq_len": 36, "label_len": 18, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 48, "seq_len": 36, "label_len": 18, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 60, "seq_len": 36, "label_len": 18, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 24, "seq_len": 104, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 36, "seq_len": 104, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 48, "seq_len": 104, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "FRED-MD.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 60, "seq_len": 104, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "m", "dataset": "FRED-MD", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/FRED-MD/GPT4TS"



