python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 24}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 24, "seq_len": 96, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 36}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 36, "seq_len": 96, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 48}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 48, "seq_len": 96, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 60}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 60, "seq_len": 96, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 24}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 24, "seq_len": 32, "label_len": 16, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 36}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 36, "seq_len": 32, "label_len": 16, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 48}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 48, "seq_len": 32, "label_len": 16, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "NASDAQ.csv" --strategy-args '{"horizon": 60}' --model-name "pre_train.TimesFM" --model-hyper-params '{"horizon": 60, "seq_len": 32, "label_len": 16, "input_patch_len": 32, "output_patch_len": 128, "target_dim": 5, "is_train": 1, "sampling_rate": 1, "dataset": "NASDAQ", "freq": "d"}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/NASDAQ/TimesFM"

