python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 24, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 36, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 48, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 60, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 17, "max_backcast_len": 96, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 24, "seq_len": 104, "label_len": 52, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 32, "max_backcast_len": 336, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 36, "seq_len": 104, "label_len": 52, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 32, "max_backcast_len": 336, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 48, "seq_len": 104, "label_len": 52, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 32, "max_backcast_len": 336, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.UniTimeModel" --model-hyper-params '{"horizon": 60, "seq_len": 104, "label_len": 52, "is_train": 1, "enc_in": 7, "stride": 16, "max_token_num": 32, "max_backcast_len": 336, "freq": "d", "dataset": "ILI", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/ILI/UniTime"