python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 24, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 36, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 48, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 60, "seq_len": 36, "label_len": 18, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 24}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 24, "seq_len": 104, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 36}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 36, "seq_len": 104, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 48}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 48, "seq_len": 104, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Covid-19.csv" --strategy-args '{"horizon": 60}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"horizon": 60, "seq_len": 104, "is_train": 1, "enc_in":948, "d_model": 32, "dataset": "Covid-19", "batch_size": 32, "freq": "d", "sampling_rate": 1}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FULL/Covid-19/TimeLLM"

