python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":96}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 96, "seq_len": 96, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":192}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 192, "seq_len": 96, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":336}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 336, "seq_len": 96, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":720}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 720, "seq_len": 96, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":96}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 96, "seq_len": 336, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":192}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 192, "seq_len": 336, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":336}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 336, "seq_len": 336, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":720}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 720, "seq_len": 336, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":96}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 96, "seq_len": 512, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":192}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 192, "seq_len": 512, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":336}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 336, "seq_len": 512, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon":720}' --model-name "LLM.GPT4TSModel" --model-hyper-params '{"horizon": 720, "seq_len": 512, "is_train": 1, "is_gpt": 1, "patch_size": 16, "pretrain": 1, "stride": 8, "gpt_layers": 3, "d_model": 768, "freeze": 1, "lr": 0.0001, "freq": "h", "dataset": "ETTh1", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "FEW/ETTh1/GPT4TS"