python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 96}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 96, "seq_len": 96, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 192}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 192, "seq_len": 96, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 336}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 336, "seq_len": 96, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 720}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 720, "seq_len": 96, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 96}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 96, "seq_len": 336, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 192}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 192, "seq_len": 336, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 336}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 336, "seq_len": 336, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 720}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 720, "seq_len": 336, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 96}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 96, "seq_len": 512, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 192}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 192, "seq_len": 512, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 336}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 336, "seq_len": 512, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "AQShunyi.csv" --strategy-args '{"horizon": 720}' --model-name "LLM.TimeLLMsModel" --model-hyper-params '{"batch_size": 16, "horizon": 720, "seq_len": 512, "is_train": 1, "enc_in": 11, "d_model": 32, "dataset": "AQShunyi", "freq": "h", "sampling_rate": 0.05}' --adapter "llm_adapter"  --gpus 4  --num-workers 1  --timeout 60000  --save-path "FEW/AQShunyi/TimeLLM"



