python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 24}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 24, "seq_len": 36, "label_len": 18, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 36}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 36, "seq_len": 36, "label_len": 18, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 48}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 48, "seq_len": 36, "label_len": 18, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 60}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 60, "seq_len": 36, "label_len": 18, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 24}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 24, "seq_len": 104, "label_len": 52, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 36}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 36, "seq_len": 104, "label_len": 52, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 48}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 48, "seq_len": 104, "label_len": 52, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"

python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ILI.csv" --strategy-args '{"horizon": 60}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"horizon": 60, "seq_len": 104, "label_len": 52, "dataset": "ILI", "freq": "min", "target_dim": 7, "is_train": 0}' --adapter "PreTrain_adapter"  --gpus 0  --num-workers 1  --timeout 60000  --save-path "ZERO/ILI/TTM"
